### ISSUE TITLE
New bookings

### ISSUE THREAD

**Issue by jampez77** [jampez77/Ryanair#12]
It would be nice to give the user a notification when a new booking is picked up by the integration

**Comment by tjorim** [comment]
If there is a simple sensor with the number of bookings coming up the user could create an automation themselves.

**Comment by jampez77** [comment]
Excellent idea! I'll add an upcoming flights sensor.

**Comment by jampez77** [comment]
Fixed in [2023.9.5](https://github.com/jampez77/Ryanair/releases/tag/2023.9.5)

**Comment by jampez77** [comment]
It's worth noting that this will need a remove / re-install to work. It _**should**_ hopefully be the last time this is required.
