### ISSUE TITLE
Airport information 

### ISSUE THREAD

**Issue by jampez77** [jampez77/Ryanair#14]
Look into adding more information about airports, most notably location so users can automate something on arrival.

As I can't find this info in the Ryanair app it might very well be out of scope for this integration.

**Comment by jampez77** [comment]
This is out of scope as the app does not provide this information.

**Comment by tjorim** [comment]
Not sure how much of a size increase this data would be, but there are airport databases from [OpenFlights](https://github.com/jpatokal/openflights) and [OurAirports](https://github.com/davidmegginson/ourairports-data).

**Comment by jampez77** [comment]
Yeah I've seen a few sources online but I think I'd be more inclined to make separate integration, or use an existing one.

I'd like to keep this to just Ryanair stuff.
