### ISSUE TITLE
Entity picture optional

### ISSUE THREAD

**Issue by jampez77** [jampez77/Ryanair#6]
There should be a check to see if a Google pic URL exists before setting it to the entity picture attribute as this will cause a crash.

**Comment by jampez77** [comment]
Solved with 2023.9.0 release

**Comment by tjorim** [comment]
I currently don't have any flights coming up but was wondering what you meant with 'entity picture'. Are you planning to add an image entity with e.g. the boarding pass QR code?

**Comment by jampez77** [comment]
So the entity picture refers to the 'googleUrlPicture' attribute in the user profile. I suspect I get this because I initially setup my account using Google sign in. Presumably this won't be the case for everyone, hence the need to make it optional.

I love the QR boarding pass idea though. I think I will write a ticket to that effect!

**Comment by jampez77** [comment]
#13

**Comment by jampez77** [comment]
QR boarding passes have been added in [2023.9.4](https://github.com/jampez77/Ryanair/releases/tag/2023.9.4)
